# Generated by Django 3.2.15 on 2022-09-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0002_comments_likes_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=64),
        ),
    ]
